### ISSUE TITLE
Delete

### ISSUE THREAD

**Issue by renans04** [renans04/OzMap#3]
## Delete

Estou tendo problemas para apagar um usuário do mongo, acredito que o erro esteja no dois ponto( : ) que vem antes do id, como mostra a primeira linha do erro

### Código

```
.delete('/del-users/:id', async (ctx) => {
  try {
    const { id } = ctx.params
    console.log(`${id}`)
    ctx.body = `${id} foi apagado do banco de dados`
    await schema.deleteOne({_id:id})
  } catch (error) {
    console.log(error)
  }
})
```

### Erro

```
:60f227ee241abd0c74b42c29
CastError: Cast to ObjectId failed for value ":60f227ee241abd0c74b42c29" (type string) at path "_id" for model "users"
    at model.Query.exec (C:\Users\renan\ozmap\developmentOneZero-projectTest\developmentOneZero-projecttest-903563a643f6\node_modules\mongoose\lib\query.js:4498:21)
    at model.Query.Query.then (C:\Users\renan\ozmap\developmentOneZero-projectTest\developmentOneZero-projecttest-903563a643f6\node_modules\mongoose\lib\query.js:4592:15)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  messageFormat: undefined,
  stringValue: '":60f227ee241abd0c74b42c29"',
  kind: 'ObjectId',
  value: ':60f227ee241abd0c74b42c29',
  path: '_id',
  reason: Error: Argument passed in must be a single String of 12 bytes or a string of 24 hex characters
      at new ObjectID (C:\Users\renan\ozmap\developmentOneZero-projectTest\developmentOneZero-projecttest-903563a643f6\node_modules\bson\lib\bson\objectid.js:59:11)
      at castObjectId (C:\Users\renan\ozmap\developmentOneZero-projectTest\developmentOneZero-projecttest-903563a643f6\node_modules\mongoose\lib\cast\objectid.js:25:12)
      at ObjectId.cast (C:\Users\renan\ozmap\developmentOneZero-projectTest\developmentOneZero-projecttest-903563a643f6\node_modules\mongoose\lib\schema\objectid.js:245:12)
      at ObjectId.SchemaType.applySetters (C:\Users\renan\ozmap\developmentOneZero-projectTest\developmentOneZero-projecttest-903563a643f6\node_modules\mongoose\lib\schematype.js:1123:12)
      at ObjectId.SchemaType._castForQuery (C:\Users\renan\ozmap\developmentOneZero-projectTest\developmentOneZero-projecttest-903563a643f6\node_modules\mongoose\lib\schematype.js:1601:15)
      at ObjectId.SchemaType.castForQuery (C:\Users\renan\ozmap\developmentOneZero-projectTest\developmentOneZero-projecttest-903563a643f6\node_modules\mongoose\lib\schematype.js:1591:15)
      at ObjectId.SchemaType.castForQueryWrapper (C:\Users\renan\ozmap\developmentOneZero-projectTest\developmentOneZero-projecttest-903563a643f6\node_modules\mongoose\lib\schematype.js:1568:20)
      at cast (C:\Users\renan\ozmap\developmentOneZero-projectTest\developmentOneZero-projecttest-903563a643f6\node_modules\mongoose\lib\cast.js:331:32)
      at model.Query.Query.cast (C:\Users\renan\ozmap\developmentOneZero-projectTest\developmentOneZero-projecttest-903563a643f6\node_modules\mongoose\lib\query.js:4937:12)
      at model.Query.Query._castConditions (C:\Users\renan\ozmap\developmentOneZero-projectTest\developmentOneZero-projecttest-903563a643f6\node_modules\mongoose\lib\query.js:1975:10)
      at model.Query.<anonymous> (C:\Users\renan\ozmap\developmentOneZero-projectTest\developmentOneZero-projecttest-903563a643f6\node_modules\mongoose\lib\query.js:2854:8)
      at model.Query._wrappedThunk [as _deleteOne] (C:\Users\renan\ozmap\developmentOneZero-projectTest\developmentOneZero-projecttest-903563a643f6\node_modules\mongoose\lib\helpers\query\wrapThunk.js:16:8)
      at C:\Users\renan\ozmap\developmentOneZero-projectTest\developmentOneZero-projecttest-903563a643f6\node_modules\kareem\index.js:370:33
      at processTicksAndRejections (internal/process/task_queues.js:75:11),
  valueType: 'string'
}
```

**Comment by raupp** [comment]
Sim, o problema é com o ":" no it. Id do mongo é um hexa (letras de a-f e numeros apeas);  Possivelmente você esta passando isso na chamada, dado que que o teu console.log ja tem os ":" :60f227ee241abd0c74b42c29

**Comment by raupp** [comment]
Sim, o problema é com o ":" no it. Id do mongo é um hexa (letras de a-f e numeros apeas);  Possivelmente você esta passando isso na chamada, dado que que o teu console.log ja tem os ":" :60f227ee241abd0c74b42c29

**Comment by renans04** [comment]
Obrigado. Vi que estava passando dois pontos na hora da requisição.
